namespace MonitoringSoftware;

public partial class App : Application
{
    public static SignalR SignalR { get; set; }
    public App(SignalR signaR)
    {
        App.SignalR = signaR;

        Syncfusion.Licensing.SyncfusionLicenseProvider.RegisterLicense("Mgo+DSMBaFt+QHJqU01hXk5Hd0BLVGpAblJ3T2ZQdVt5ZDU7a15RRnVfRF1iSXlTfkBkXndfcw==;Mgo+DSMBPh8sVXJ1S0R+WlpFdEBBXHxAd1p/VWJYdVt5flBPcDwsT3RfQF5jT35SdkJjUXpZeHRVRQ==;ORg4AjUWIQA/Gnt2VFhiQldPd11dXmJWd1p/THNYflR1fV9DaUwxOX1dQl9gSXhTd0VkWXdbd3xUQGM=;MjI4MTY3M0AzMjMxMmUzMDJlMzBqNmdjZlBrU3h1VkpzK2hpZVlBQ3JqSk9DWFBhaDZseDhUTFljb1RRY01jPQ==;MjI4MTY3NEAzMjMxMmUzMDJlMzBtUjBHaEtkbHRqS0w2aHoxZlBNOTFKczl1OU1BdkM0OXJXaHFiRXpWMnRNPQ==;NRAiBiAaIQQuGjN/V0d+Xk9CfV5AQmBIYVp/TGpJfl96cVxMZVVBJAtUQF1hSn5VdkRjXn9WdXNdT2df;MjI4MTY3NkAzMjMxMmUzMDJlMzBlOXUrUVlsb2o1d1czK3VmQllLcjNMOTRENDl3R2tkNDZ6ZEZ3ZHVLWnA4PQ==;MjI4MTY3N0AzMjMxMmUzMDJlMzBnSTA4ZmZJZDIwRnhSMVU1RERFZXFQa1FqNDZWaGFQZkdXMm9UYzZoUzlVPQ==;Mgo+DSMBMAY9C3t2VFhiQldPd11dXmJWd1p/THNYflR1fV9DaUwxOX1dQl9gSXhTd0VkWXdbd31SRWM=;MjI4MTY3OUAzMjMxMmUzMDJlMzBFUUhMN052YURROHhoTGVtV0ZiZUJQaGxEZXc1UlhSdnZ5ajVPNU52T1VvPQ==;MjI4MTY4MEAzMjMxMmUzMDJlMzBCUDhTcW9CanBmSW52S04zenR4NDh0MzBoQjREMkR4cjU2SUVkY0t1amxnPQ==;MjI4MTY4MUAzMjMxMmUzMDJlMzBlOXUrUVlsb2o1d1czK3VmQllLcjNMOTRENDl3R2tkNDZ6ZEZ3ZHVLWnA4PQ==");
        InitializeComponent();
        MainPage = new AppShell();
    }
}